# 自定义包配置文件
# 格式: <仓库URL> <目标目录> [分支]
# 
# 说明:
# 0. 主要是small8源以外的包，small8源的包可以直接在update.sh中install_small8() 函数下直接添加
# 1. 应用包: package/luci-app-xxx
# 2. 依赖包: package/xxx (核心依赖)
# 3. 中文化: package/luci-i18n-xxx-zh-cn


# ===== 系统工具 =====
https://github.com/sirpdboy/luci-app-partexp package/luci-app-partexp

# ===== 网络工具 =====
https://github.com/sirpdboy/luci-app-ddns-go package/ddns-go


# ===== SMB 服务 =====
https://github.com/sbwml/smbuser package/smbuser
https://github.com/sbwml/luci-app-smbuser package/luci-app-smbuser
https://github.com/sbwml/luci-i18n-smbuser-zh-cn package/luci-i18n-smbuser-zh-cn

# ===== 定时任务 =====
https://github.com/sirpdboy/luci-app-taskplan package/luci-app-taskplan
# https://github.com/sirpdboy/luci-i18n-taskplan-zh-cn package/luci-i18n-taskplan-zh-cn

# ===== 广告过滤 =====