name: Auto.rls.AA test
run-name: Autorls.test - ${{ inputs.model }}

on:
  schedule:
    # 北京时间12:20（UTC时间04:15）
    - cron: '20 4 * * *'  # 每日UTC 4:20触发[6,7](@ref)
  
  workflow_dispatch:
    inputs:
      model:
        required: true
        description: Device Model
        type: choice
        default: Arthur_Athena_immwrt
        options:
          - Arthur_Athena_immwrt
          - Arthur_Athena_Lite
      runs-on:
        required: true
        description: Runs on...
        type: choice
        default: ubuntu-22.04 
        options:
          - ubuntu-22.04

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ${{ inputs.runs-on || 'ubuntu-20.04' }}  # 默认值同步修改
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"
          remove-large-packages: "true"
          remove-cached-tools: "true"
          remove-swapfile: "true"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo bash <(curl -sL https://build-scripts.immortalwrt.org/init_build_environment.sh)
          sudo apt -y install dos2unix libfuse-dev
          sudo apt -y autoremove --purge
          sudo apt clean
          sudo timedatectl set-timezone Asia/Shanghai

      - name: Initialization Values
        run: |
          MODEL_NAME="${{ inputs.model || 'Arthur_Athena_immwrt' }}"
          echo "MODEL_NAME=$MODEL_NAME" >> $GITHUB_ENV
          export BUILD_DATE=$(TZ=Asia/Shanghai date +"%y.%m.%d_%H.%M.%S")
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
          BUILD_SRC=$(awk -F"=" '/REPO_URL/ {print $NF}' "./compilecfg/$MODEL_NAME.ini")
          echo "BUILD_SRC=$BUILD_SRC" >> $GITHUB_ENV

      - name: Pre Clone
        run: ./pre_clone_action.sh ${{ env.MODEL_NAME }}

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ./action_build/.ccache
            ./action_build/staging_dir
          key: ${{ runner.os }}-${{ env.MODEL_NAME }}-${{ hashFiles('**/repo_flag') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.MODEL_NAME }}-

      - name: Refresh the cache
        run: |
          find "./action_build/staging_dir" -type d -name "stamp" -not -path "*target*" -exec touch {} +

      - name: Build Firmware
        run: ./build.sh ${{ env.MODEL_NAME }}

      - name: Get Kernel Version
        run: |
          KVER=$(find ./action_build/dl -name 'linux-*.tar.xz' -printf '%f\n' | grep -Po '\d+\.\d+\.\d+' | sort -Vr | head -1)
          echo "KVER=${KVER:-unknown}" >> $GITHUB_ENV

      - name: Install GitHub CLI
        run: sudo apt update && sudo apt install -y gh

      - name: Delete Old Cache
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh cache list --key "${{ runner.os }}-${{ env.MODEL_NAME }}" --json key -q '.[].key' | \
          while read -r key; do
            gh cache delete "$key" --confirm
          done
          echo "========cache status========"
          echo "ccache: $(du -sh ./action_build/.ccache | cut -f 1)"
          echo "staging: $(du -sh ./action_build/staging_dir | cut -f 1)"

      - name: Machine Information
        run: |
          echo "=============================================="
          lscpu | grep -E "name|Core|Thread"
          echo "=============================================="
          df -h
          echo "=============================================="

      - name: Prepare Release Body
        run: |
          cat <<EOF > release_body.txt
          云编译发布
          源码：${{ env.BUILD_SRC }}
          Kernel: ${{ env.KVER }}
          亚瑟/雅典娜禁用Docker/Coremark/mwan3
          WIFI密码: 12345678
          LAN地址: 192.168.111.1
          插件：
          $(grep -hoP "luci-app-\w+" ./firmware/*.manifest | sort -u)
          EOF

      - name: Release Firmware
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.BUILD_DATE }}_${{ env.MODEL_NAME }}
          files: ./firmware/*.*
          body_path: ./release_body.txt
